import json
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from pydantic import BaseModel, create_model
from typing import List, Optional, Dict, Any
from dependency import *
import io
from fastapi.responses import StreamingResponse, FileResponse
import pandas as pd
import os
import shutil
import pdfplumber
from uuid import uuid4
from model import Chat, Message, Folder, User
from sqlmodel import Session, select
import requests

UPLOAD_DIR = "./uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

router = APIRouter(prefix="/chat", tags=["Chat"])

# HF_API_URL = "https://z7zxrhb7h2wgz7uj.us-east-1.aws.endpoints.huggingface.cloud"


# --- SCHEMAS ---
class UserQuery(BaseModel):
    text: str
    chat_id: int
    # chat_id: str
    columns: List[str]
    model: str = "local"
    file_name: Optional[str] = None
    file_size: Optional[int] = None


class ScriptQuery(BaseModel):
    cases: List[
        Dict[str, Any]
    ]  # Accepts the JSON array generated by the previous API
    chat_id: int
    model: str = "local"


class ChatMove(BaseModel):
    folder_id: Optional[int] = None


class ChatCreate(BaseModel):
    name: str
    user_id: int
    chat_type: str = "test_case"  # "test_case" | "test_script"


class ChatRename(BaseModel):
    name: str


class DownloadQuery(BaseModel):
    cases: List[Dict[str, Any]]


# --- HELPER: CONSTRUCT PROMPT ---
def build_dynamic_json_schema(columns: List[str]) -> dict:
    """Dynamically creates a Pydantic schema for an ARRAY of test cases."""
    fields = {}
    list_columns = ["prerequisites", "steps", "data", "expected"]

    # Define which columns the LLM is actually allowed to generate content for
    generatable_columns = [
        "id",
        "scenario",
        "prerequisites",
        "steps",
        "data",
        "expected",
    ]

    for col in columns:
        if col in list_columns:
            fields[col] = (List[str], ...)
        elif col in generatable_columns:
            fields[col] = (str, ...)
        else:
            # Force 'actual', 'status', and any other custom column to be strictly null
            fields[col] = (type(None), None)

    # 1. Create the schema for a SINGLE test case
    SingleTestCase = create_model("SingleTestCase", **fields)

    # 2. Create a WRAPPER schema that holds a LIST of single test cases
    TestCaseList = create_model("TestCaseList", cases=(List[SingleTestCase], ...))

    # Return the JSON schema dictionary for the wrapper
    return TestCaseList.model_json_schema()


def extract_use_cases(pdf_path):
    """Your existing semantic parsing logic goes here."""
    all_rows = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            tables = page.extract_tables()
            for table in tables:
                cleaned_rows = [row for row in table if any(row)]
                all_rows.extend(cleaned_rows)

    use_cases = []
    current_buffer = []
    for row in all_rows:
        if len(row) < 2:
            continue
        field = row[0].strip() if row[0] else ""
        value = row[1].strip() if row[1] else ""

        if "Use Case Name" in field or "Use Case ID" in field:
            if "Use Case Name" in field and current_buffer:
                use_cases.append("\n".join(current_buffer))
                current_buffer = []

        if field:
            current_buffer.append(f"\n### {field}:")
        if value:
            current_buffer.append(value)

    if current_buffer:
        use_cases.append("\n".join(current_buffer))

    return use_cases


# --- ENDPOINT ---
@router.get("/")
def health_check():
    return {"health": "OK"}


@router.post("/", status_code=201)
def create_new_chat(chat_data: ChatCreate, session: Session = Depends(get_db_session)):
    """Creates a fresh, empty chat session."""
    new_chat = Chat(name=chat_data.name, user_id=chat_data.user_id, chat_type=chat_data.chat_type)
    session.add(new_chat)
    session.commit()
    session.refresh(new_chat)
    return new_chat


@router.get("/user/{user_id}")
def get_user_chats(user_id: int, session: Session = Depends(get_db_session)):
    """Fetches all chats for the sidebar, ordered by newest first."""
    statement = (
        select(Chat).where(Chat.user_id == user_id).order_by(Chat.created_at.desc())
    )
    return session.exec(statement).all()


@router.post("/test-case")
def generate_test_case(
    query: UserQuery,
    llm=Depends(get_test_case_llm),
    embedder=Depends(get_embedding_model),
    collection=Depends(get_rag_collection),
    session: Session = Depends(get_db_session),  # <--- Inject Database Session
):
    # 1. Verify Chat & Save User Message (Same as before)
    # 1. Verify Chat & User
    chat = session.get(Chat, query.chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat session not found")

    user = session.get(User, chat.user_id)

    user_msg = Message(
        chat_id=query.chat_id,
        role="user",
        content=query.text,
        file_name=query.file_name,
        file_size=query.file_size,
    )
    session.add(user_msg)
    session.commit()
    print(query)

    # 2. RAG Retrieval (Same as before - happens locally regardless of LLM choice)
    query_vec_resp = embedder.create_embedding(query.text)
    query_vec = query_vec_resp["data"][0]["embedding"]

    results = collection.query(
        query_embeddings=[query_vec], n_results=3, where={"chat_id": str(query.chat_id)}
    )

    if results["documents"] and results["documents"][0]:
        context_text = results["documents"][0]
    else:
        context_text = (
            "No specific documentation provided. Rely on general QA best practices."
        )

    dynamic_schema = build_dynamic_json_schema(query.columns)

    messages = [
        {
            "role": "system",
            "content": f"<|im_start|>system\nYou are a test case generator. You are to only generate a JSON array of test cases based on a given requirement according to best practices. Consider edge cases and negative cases when possible. Each case must have the following keys: {query.columns}. Keep text in test cases concise and imperative. Output your answer in 'cases' array.\n\nDocumentation Context:\n{context_text}<|im_end|>",
        },
        {
            "role": "user",
            "content": f"<|im_start|>user\nGenerate test cases for the following requirement: {query.text}<|im_end|>",
        },
    ]

    # 3. ROUTE THE INFERENCE REQUEST
    try:
        if query.model == "cloud":
            # Check if user has saved a token
            if not user.hf_token:
                raise HTTPException(status_code=400, detail="Hugging Face token not found.")
            if not user.hf_endpoint_url:
                raise HTTPException(status_code=400, detail="Hugging Face Endpoint URL not found. Please add it in Profile settings.")

            # Use the token from the database
            # --- CALL DEPLOYED MODEL ---
            headers = {
                "Authorization": f"Bearer {user.hf_token}",
                "Content-Type": "application/json",
            }

            payload = {
                "inputs": {
                    "target_model": "test_case",  # Routes to Qwen3-4B-Instruct
                    "messages": messages,
                    "temperature": 0.1,
                    "max_tokens": 2048,
                    "repeat_penalty": 1.05,
                    "response_format": {
                        "type": "json_schema",
                        "schema": dynamic_schema,
                    },
                    "stop": ["<|im_end|>"],
                }
            }

            response = requests.post(user.hf_endpoint_url, headers=headers, json=payload)

            if response.status_code != 200:
                raise HTTPException(
                    status_code=502, detail=f"Hugging Face API Error: {response.text}"
                )

            hf_data = response.json()
            raw_json_string = hf_data["choices"][0]["message"]["content"]

        else:
            # --- CALL LOCAL MODEL ---
            output = llm.create_chat_completion(
                messages=messages,
                response_format={"type": "json_schema", "schema": dynamic_schema},
                temperature=0.1,
                max_tokens=2048,
                repeat_penalty=1.05,
                stop=["<|im_end|>"],
            )
            raw_json_string = output["choices"][0]["message"]["content"]

        # 4. Parse JSON and Save Response
        data = json.loads(raw_json_string)

        ai_msg = Message(
            chat_id=query.chat_id, role="assistant", content=json.dumps(data)
        )

        session.add(ai_msg)
        session.commit()

        data["retrieved_context"] = context_text

        return data

    except json.JSONDecodeError:
        print(f"Failed JSON Output: {raw_json_string}")
        raise HTTPException(
            status_code=500, detail="The selected model failed to return valid JSON."
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/test-script")
def generate_test_script(
    query: ScriptQuery,
    llm=Depends(get_test_script_llm),
    session: Session = Depends(get_db_session),
):
    # 1. Verify Chat & User
    chat = session.get(Chat, query.chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat session not found")

    user = session.get(User, chat.user_id)

    # Convert the JSON array back to a string for the LLM prompt and DB storage
    test_cases_str = json.dumps(query.cases, indent=2)

    # Save user message (The JSON payload acts as the user prompt)
    user_msg = Message(chat_id=query.chat_id, role="user", content=test_cases_str)
    session.add(user_msg)
    session.commit()

    # 2. Define Prompts
    messages = [
        {
            "role": "system",
            "content": "<|im_start|>system\nYou are a Playwright test script generator. You are to only generate Playwright script in Typescript based on a given JSON array of test cases according to best practices. Keep the code clean, consistent, and especially readable. Output ONLY valid executable Typescript code without markdown code blocks. Use 'getBy*' methods and placeholder names.<|im_end|>",
        },
        {
            "role": "user",
            "content": f"<|im_start|>user\nGenerate a Playwright test script for the following test cases:\n{test_cases_str}<|im_end|>",
        },
    ]

    # 3. ROUTE THE INFERENCE REQUEST
    try:
        if query.model == "cloud":
            if not user.hf_token:
                raise HTTPException(status_code=400, detail="Hugging Face token not found.")
            if not user.hf_endpoint_url:
                raise HTTPException(status_code=400, detail="Hugging Face Endpoint URL not found. Please add it in Profile settings.")

            headers = {
                "Authorization": f"Bearer {user.hf_token}",
                "Content-Type": "application/json",
            }

            payload = {
                "inputs": {
                    "target_model": "test_script",  # Routes to Qwen2.5-Coder-7B
                    "messages": messages,
                    "temperature": 0.1,
                    "max_tokens": 2048,  # Increased for code generation
                    "repeat_penalty": 1.05,
                    "stop": ["<|im_end|>"],
                    # Notice: response_format is intentionally removed to allow raw code output
                }
            }

            response = requests.post(user.hf_endpoint_url, headers=headers, json=payload)

            if response.status_code != 200:
                raise HTTPException(
                    status_code=502, detail=f"Hugging Face API Error: {response.text}"
                )

            hf_data = response.json()
            generated_code = hf_data["choices"][0]["message"]["content"]

        else:
            # --- CALL LOCAL MODEL ---
            output = llm.create_chat_completion(
                messages=messages,
                temperature=0.1,
                max_tokens=2048,
                repeat_penalty=1.05,
                stop=["<|im_end|>"],
            )
            generated_code = output["choices"][0]["message"]["content"]

        # 4. Save and Return Response
        # Clean up Markdown backticks if the model ignored the system prompt
        if generated_code.startswith("```"):
            generated_code = "\n".join(generated_code.split("\n")[1:-1])

        ai_msg = Message(
            chat_id=query.chat_id, role="assistant", content=generated_code
        )

        session.add(ai_msg)
        session.commit()

        return {"code": generated_code}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/download")
async def download_test_cases(query: DownloadQuery):
    if not query.cases:
        raise HTTPException(status_code=400, detail="No test cases provided")

    processed_cases = []

    # Process data for CSV compatibility
    for item in query.cases:
        processed_item = {}
        for key, value in item.items():
            if isinstance(value, list):
                if key == "steps":
                    # Numbered list for steps
                    processed_item[key] = "\n".join(
                        f"{i+1}. {step}" for i, step in enumerate(value)
                    )
                else:
                    # Bulleted list for other list types (prerequisites, data, expected)
                    processed_item[key] = "\n".join(f" - {v}" for v in value)
            elif value is None:
                # Catch the null fields (like 'actual', 'status') and convert to empty strings for the CSV
                processed_item[key] = ""
            else:
                processed_item[key] = value

        processed_cases.append(processed_item)

    # Create Pandas DataFrame directly from the processed dictionaries
    df = pd.DataFrame(processed_cases)

    # Write CSV to an in-memory buffer
    stream = io.StringIO()
    df.to_csv(stream, index=False, encoding="utf-8")

    # Prepare the response
    response = StreamingResponse(iter([stream.getvalue()]), media_type="text/csv")
    response.headers["Content-Disposition"] = "attachment; filename=test_cases.csv"

    return response


@router.post("/upload")
async def upload_document(
    chat_id: str = Form(...),
    file: UploadFile = File(...),
    embed_model=Depends(get_embedding_model),
    collection=Depends(get_rag_collection),
):
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported.")

    # 1. Save file permanently in ./uploads/{chat_id}/
    chat_upload_dir = os.path.join(UPLOAD_DIR, str(chat_id))
    os.makedirs(chat_upload_dir, exist_ok=True)
    permanent_path = os.path.join(chat_upload_dir, file.filename)

    with open(permanent_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    try:
        # 2. Extract Use Cases
        documents = extract_use_cases(permanent_path)
        if not documents:
            raise HTTPException(status_code=400, detail="No extractable text found.")

        # 3. Embed and Store
        for doc in documents:
            response = embed_model.create_embedding(doc)
            vector = response["data"][0]["embedding"]

            collection.add(
                documents=[doc],
                embeddings=[vector],
                metadatas=[
                    {
                        "source": file.filename,
                        "type": "use_case_spec",
                        "chat_id": chat_id,
                    }
                ],
                ids=[str(uuid4())],
            )

        return {
            "message": "Document ingested successfully.",
            "use_cases_found": len(documents),
            "chat_id": chat_id,
        }

    except HTTPException:
        raise
    except Exception as e:
        if os.path.exists(permanent_path):
            os.remove(permanent_path)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{chat_id}/files")
def list_chat_files(chat_id: int, session: Session = Depends(get_db_session)):
    """Lists uploaded PDF filenames for a given chat (from Message records)."""
    statement = (
        select(Message)
        .where(Message.chat_id == chat_id, Message.file_name != None)
        .order_by(Message.timestamp)
    )
    messages = session.exec(statement).all()
    seen = set()
    files = []
    for msg in messages:
        if msg.file_name and msg.file_name not in seen:
            seen.add(msg.file_name)
            files.append({
                "file_name": msg.file_name,
                "file_size": msg.file_size,
            })
    return files


@router.get("/{chat_id}/file/{filename}")
def download_chat_file(chat_id: int, filename: str):
    """Downloads a previously uploaded PDF for a chat."""
    safe_name = os.path.basename(filename)
    file_path = os.path.join(UPLOAD_DIR, str(chat_id), safe_name)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(
        path=file_path,
        media_type="application/pdf",
        filename=safe_name,
    )


@router.get("/{chat_id}/history")
def get_chat_history(chat_id: int, session: Session = Depends(get_db_session)):
    # Verify chat exists
    chat = session.get(Chat, chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")

    # Query messages related to this chat, ordered by creation time
    statement = (
        select(Message).where(Message.chat_id == chat_id).order_by(Message.timestamp)
    )
    messages = session.exec(statement).all()

    return messages


@router.patch("/{chat_id}/move")
def move_chat(
    chat_id: int, move_data: ChatMove, session: Session = Depends(get_db_session)
):
    # 1. Verify the chat exists
    chat = session.get(Chat, chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")

    # 2. If moving INTO a folder, verify the folder exists
    if move_data.folder_id is not None:
        folder = session.get(Folder, move_data.folder_id)
        if not folder:
            raise HTTPException(status_code=404, detail="Target folder not found")

    # 3. Update and save
    chat.folder_id = move_data.folder_id
    session.add(chat)
    session.commit()
    session.refresh(chat)

    status_msg = (
        f"Moved to folder {move_data.folder_id}"
        if move_data.folder_id
        else "Removed from folder"
    )
    return {"message": status_msg, "chat_id": chat.id, "folder_id": chat.folder_id}


@router.delete("/{chat_id}")
def delete_chat(
    chat_id: int,
    session: Session = Depends(get_db_session),
    collection=Depends(get_rag_collection),
):
    # 1. Verify chat exists
    chat = session.get(Chat, chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")

    # 2. Delete Messages from SQLite
    statement = select(Message).where(Message.chat_id == chat_id)
    messages = session.exec(statement).all()
    for msg in messages:
        session.delete(msg)

    # 3. Delete Document Vectors from ChromaDB
    # This prevents orphaned vector data from taking up disk space
    collection.delete(where={"chat_id": str(chat_id)})

    # 4. Delete uploaded files from disk
    chat_upload_dir = os.path.join(UPLOAD_DIR, str(chat_id))
    if os.path.exists(chat_upload_dir):
        shutil.rmtree(chat_upload_dir)

    # 5. Delete Chat from SQLite
    session.delete(chat)
    session.commit()

    return {"message": f"Chat {chat_id} and its associated data deleted successfully"}


@router.patch("/{chat_id}/rename")
def rename_chat(
    chat_id: int, rename_data: ChatRename, session: Session = Depends(get_db_session)
):
    # 1. Verify chat exists
    chat = session.get(Chat, chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")

    # 2. Update name and save
    chat.name = rename_data.name
    session.add(chat)
    session.commit()
    session.refresh(chat)

    return {
        "message": "Chat renamed successfully",
        "chat_id": chat.id,
        "new_name": chat.name,
    }